### ISSUE TITLE
Using Agama, we can't set deviceType but always get 'tv'

### ISSUE THREAD

**Issue by josefnorlin** [THEOplayer/react-native-theoplayer-analytics#131] opened 2023-12-18 15:04 UTC
We're looking to separate our AndroidTV app from our STB AndroidTV-launcher.

Looking in the documentation it looks as we can set deviceType in the agamaConfig, but no matter what we set there we always get deviceType: 'tv'.

Looking at the code in DeviceInfo.ts:

```
export function getAgamaDeviceType(): AgamaDeviceType | undefined {
  return (Platform.OS === 'web') ? getAgamaDeviceTypeWeb() : getAgamaDeviceTypeNative();
}

function getAgamaDeviceTypeNative(): AgamaDeviceType | undefined {
  return Platform.isTV ? 'tv' : DetectableDeviceType.MOBILE_;
}
```

It looks as the reason is that if Platform.isTV we always get 'tv' as deviceType, which could correlate to our findings.

Even if we send:

`{"application": "xxxxxx", "applicationVersion": "xxxxx", "config": "emp_service=https://agama.tv.telenor.se:443/report;report_interval=30;id_report_interval=240;operator_id=xxxxxxx", "deviceID": "00000000-0000-0000-0000-xxxxxxxxx", "deviceManufacturer": "xxxx", "deviceModel": "xxxxxxx", "deviceType": "media-streamer", "integration": "agama", "logLevel": "info", "userAccountID": "xxxxxxx"}`

It shows up as deviceType: 'tv'

Tested on theoplayer/react-native-analytics-agama version 1.2.1

**Comment by wjoosen** [comment] 2023-12-20 12:07
> Looking in the documentation it looks as we can set deviceType in the agamaConfig, but no matter what we set there we always get deviceType: 'tv'.

Which documentation suggests that this is possible? If you check the [AgamaConfiguration interface](https://github.com/THEOplayer/react-native-theoplayer-analytics/blob/main/agama/src/api/AgamaConfiguration.ts), you'll see that this property is not available and thus will be disregarded if you provide it anyway. 

Confusion may be caused by the [AgamaPlayerConfiguration documentation](https://docs.theoplayer.com/api-reference/web/theoplayer.agamaplayerconfiguration.md#devicetype) of the THEOplayer Web SDK's Agama integration. This is a different integration than the react native integration you're reporting this issue for. 

We'll review your feature request. In the meantime, feel free to contribute or to make changes to your fork of react-native-theoplayer-analytics if you want to speed things up.

Kind regards,
Wonne

**Comment by tvanlaerhoven** [comment] 2024-06-06 12:49
@josefnorlin closing this ticket for now; please reach out to us if you still see issues.

**Closed by tvanlaerhoven** 2024-06-06 12:49 UTC
